// penyisihan.eec.technocorner.id/pages/signin.tsx
import toast from "react-hot-toast";
import HtmlHead from "../components/HtmlHead";
import { toastLoading } from "../lib/toast";

const SignIn = ({ signIn }: { signIn: Function }) => {
  async function submitHandler(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const loadingToast = toastLoading();

    const target = event.target as typeof event.target & {
      teamId: { value: string };
      userEmail: { value: string };
    };

    const teamId = target.teamId.value;
    const userEmail = target.userEmail.value;

    await signIn({ teamId, userEmail });

    toast.dismiss(loadingToast);
  }

  return (
    <>
      <HtmlHead title="Masuk" />
      <div className="min-w-screen min-h-screen flex items-center justify-center bg-zinc-200">
        <form
          onSubmit={submitHandler}
          className="w-11/12 sm:w-[30rem] p-4 sm:p-8 flex flex-col items-center transform-gpu bg-zinc-50 rounded-3xl border border-black"
        >
          <h1 className="font-bold text-xl">MASUK</h1>
          <div className="mt-2 sm:mt-6 w-full flex flex-col">
            <div>
              <p className="font-bold">
                ID Tim{" "}
                <span className="font-normal text-black/50">
                  (Dapat dilihat pada laman dasbor tim)
                </span>
              </p>
              <input
                name="teamId"
                type="text"
                placeholder="Masukkan ID tim"
                required
                className="w-full py-0.5 sm:py-2.5 px-3 border-2 focus-within:border-sky-500 rounded-xl bg-transparent outline-none"
              />
            </div>
            <div className="mt-4">
              <p className="font-bold">Email</p>
              <input
                name="userEmail"
                type="text"
                placeholder="Masukkan email anggota tim"
                required
                className="w-full py-0.5 sm:py-2.5 px-3 border-2 focus-within:border-sky-500 rounded-xl bg-transparent outline-none"
              />
            </div>
            <button
              className="w-full mt-6 py-1.5 rounded-full bg-[#04BFAD] sm:leading-7 font-bold text-white"
              type="submit"
            >
              Masuk
            </button>
          </div>
        </form>
      </div>
    </>
  );
};

export default SignIn;

// final.eec.technocorner.id/components/SignIn.vue
<template>
  <div
    v-if="show"
    @click="closeModal"
    class="absolute w-full h-full flex justify-center items-center transform-gpu bg-slate-200/10 backdrop-blur-sm"
  >
    <div
      @click.stop=""
      class="w-11/12 sm:w-96 p-4 sm:p-6 flex flex-col items-center transform-gpu bg-slate-50 rounded-3xl border border-black"
    >
      <p class="font-bold">MASUK</p>
      <form
        @submit.prevent="submitHandler"
        class="mt-2 sm:mt-4 w-full flex flex-col text-xs"
      >
        <p class="font-bold">ID Tim</p>
        <input
          name="code"
          type="text"
          placeholder="Masukkan ID tim"
          autocomplete="off"
          required
          class="my-1 sm:my-2 py-0.5 sm:py-2.5 px-3 border-2 border focus-within:border-sky-500 rounded-xl bg-transparent outline-none autofill:caret-white"
        />
        <p class="text-black/30">ID tim dapat dilihat pada laman dasbor tim</p>
        <button
          class="w-full mt-6 py-1.5 rounded-full bg-[#04BFAD] sm:leading-7 font-bold text-white"
          type="submit"
        >
          Masuk
        </button>
      </form>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { postData } from "~~/libs/fetch";
import statusCode from "~~/libs/statusCode";

export default defineComponent({
  props: { show: Boolean, wsCode: String },
  methods: {
    closeModal() {
      this.$emit("close");
    },
    async submitHandler(event: Event) {
      const target = event.target as typeof event.target & {
        code: { value: string };
      };
      const code = target.code.value;

      const { status, json } = await postData("/auth/signin", {
        code,
      });

      if (status != statusCode.OK || !json) {
        alert(`${json && json.error ? json.error : "Terjadi galat"}`);
        return;
      }

      this.$emit("signedIn", json);
      this.closeModal();
    },
  },
});
</script>
